# Generated by Django 3.1.2 on 2020-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('catageries', models.CharField(max_length=100)),
                ('qauntitie', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
