# Generated by Django 3.1.2 on 2020-10-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='location',
        ),
    ]
