# Generated by Django 3.1.2 on 2020-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_wishlist_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.AddField(
            model_name='products',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='wquantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
