# Generated by Django 3.1.2 on 2020-10-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201027_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
